CUDA_VISIBLE_DEVICES="0" python ./t2t_bert/distributed_bin/evaluate_api.py \
	--buckets "/data/xuht" \
	--config_file "/data/xuht/chinese_L-12_H-768_A-12/bert_config.json" \
	--init_checkpoint "porn/clean_data/normal/model/estimator/all_reduce_4_adam_weight_0228/model.ckpt-79344" \
	--vocab_file "/data/xuht/chinese_L-12_H-768_A-12/vocab.txt" \
	--label_id "/data/xuht/porn/label_dict.json" \
	--max_length 128 \
	--train_file "porn/clean_data/normal/train_tfrecords" \
	--dev_file "porn/clean_data/normal/dev_tfrecords" \
	--model_output "porn/clean_data/normal/model/estimator/all_reduce_4_adam_weight_0228/" \
	--epoch 8 \
	--num_classes 5 \
	--train_size 1402171 \
	--eval_size 145019 \
	--batch_size 24 \
	--model_type "bert" \
	--if_shard 2 \
	--is_debug 1 \
	--run_type "sess" \
	--opt_type "all_reduce" \
	--num_gpus 4 \
	--parse_type "parse_batch" \
	--rule_model "normal" \
	--profiler "no" \
	--train_op "adam_weight_decay_exclude" \
	--running_type "eval" \
	--cross_tower_ops_type "paisoar" \
	--distribution_strategy "MirroredStrategy"
