python ./t2t_bert/data_generator/create_span_bert_pretrain_dataset_efficiency.py \
        --buckets /data/xuht \
        --input_file /data/xuht/english_corpus/wiki_book_corpus.txt \
        --output_file /data/xuht/english_corpus/pretrain_single_random_gan_uncased \
        --vocab_file ./data/uncased_L-12_H-768_A-12/vocab.txt \
        --word_piece_model mrc_search/sentence_piece/mrc_search_bpe.model \
        --do_lower_case true \
        --max_seq_length 512 \
        --max_predictions_per_seq 78 \
        --dupe_factor 1 \
        --tokenizer_type 'word_piece' \
        --do_whole_word_mask true \
        --es_user_name mrc_search_4l \
        --password K9cb1bd713507 \
        --doc_index en_wiki_book \
        --doc_type _doc