mpirun -np 2 \
 -H localhost:2 \
 python ./t2t_bert/distributed_bin/hvd_train_eval_api.py \
 --buckets "/data/xuht" \
 --config_file "/data/xuht/chinese_L-12_H-768_A-12/bert_config.json" \
 --init_checkpoint "chinese_L-12_H-768_A-12/bert_model.ckpt" \
 --vocab_file "/data/xuht/chinese_L-12_H-768_A-12/vocab.txt" \
 --label_id "/data/xuht/lcqmc/data/label_dict.json" \
 --max_length 128 \
 --train_file "lcqmc/data/distillation/train_tfrecords" \
 --dev_file "lcqmc/data/distillation/dev_tfrecords" \
 --model_output "lcqmc/data/model/estimator/siamese_cnn_interaction_0316" \
 --epoch 5 \
 --num_classes 2 \
 --train_size 238766 \
 --eval_size 8802 \
 --batch_size 32 \
 --model_type "textcnn" \
 --if_shard 1 \
 --is_debug 1 \
 --run_type "sess" \
 --opt_type "hvd" \
 --num_gpus 4 \
 --parse_type "parse_batch" \
 --rule_model "normal" \
 --profiler "no" \
 --train_op "adam" \
 --running_type "train" \
 --cross_tower_ops_type "paisoar" \
 --distribution_strategy "MirroredStrategy" \
 --load_pretrained "no" \
 --w2v_path "w2v/tencent_ai_lab/char_w2v.txt" \
 --with_char "no_char" \
 --input_target "a" \
 --decay "no" \
 --warmup "no" \
 --distillation "normal" \
 --temperature 2.0 \
 --distillation_ratio 0.5 \
 --task_type "pair_sentence_classification" \
 --classifier "siamese_interaction_classifier"


