python ./t2t_bert/distributed_data_prepare/language_model_data_prepare.py \
	--buckets /data/xuht \
	--train_file product_lm/train.txt \
	--dev_file product_lm/test.txt \
	--test_file product_lm/test.txt \
	--train_result_file product_lm/data/train_tfrecords \
	--dev_result_file product_lm/data/dev_tfrecords \
	--test_result_file product_lm/data/test_tfrecords \
	--vocab_file ./data/chinese_L-12_H-768_A-12/vocab.txt \
	--lower_case "true" \
	--do_whole_word_mask "false" \
	--max_length 64 \
	--data_type "fasttext" \
	--tokenizer_type full_bpe