python ./t2t_bert/distributed_data_prepare/bert_distillation_data_prepare.py \
	--buckets /data/xuht \
	--train_file sentence_similarity/multilingual_merged_train.json \
	--dev_file sentence_similarity/multilingual_merged_dev.json \
	--test_file sentence_similarity/multilingual_merged_test.json \
	--train_result_file sentence_similarity/data/model/match_pyramid/train_tfrecords \
	--dev_result_file sentence_similarity/data/model/match_pyramid/dev_tfrecords\
	--test_result_file sentence_similarity/data/model/match_pyramid/test_tfrecords\
	--supervised_distillation_file sentence_similarity/data/model/distillation/train_distillation_result.info \
	--unsupervised_distillation_file sentence_similarity/data/model/distillation/dev_distillation_result.info \
	--vocab_file ./data/multi_cased_L-12_H-768_A-12/vocab.txt \
	--label_id /data/xuht/lcqmc/data/label_dict.json \
	--lower_case True \
	--max_length 64 \
	--if_rule "no_rule" \
	--rule_word_dict /data/xuht/porn/rule/rule/phrases.json \
	--rule_word_path /data/xuht/porn/rule/rule/mined_porn_domain_adaptation_v2.txt \
	--rule_label_dict /data/xuht/porn/rule/rule/rule_label_dict.json \
	--with_char "no" \
	--char_len 5 \
	--predefined_vocab_size 50000 \
	--corpus_vocab_path lcqmc/data/distillation_bpe/char_id.txt \
	--data_type "lcqmc" \
	--if_add_unlabeled_distillation "no" \
	--tokenizer_type "full_bpe"
