CUDA_VISIBLE_DEVICES="" python ./t2t_bert/pretrain_finetuning/export_api.py \
 --buckets "/data/xuht" \
 --config_file "/data/xuht/light_conv_multilingual/textcnn_multilingual_embedding_light_dgcnn_v1.json" \
 --model_dir "light_conv_multilingual/export" \
 --init_checkpoint "light_conv_multilingual/model.ckpt-120000" \
 --model_output "light_conv_multilingual/model.ckpt-120000" \
 --max_length 256 \
 --export_dir "light_conv_multilingual/export" \
 --num_classes 2 \
 --input_target "" \
 --model_scope "textcnn" \
 --model_type "gated_cnn_seq" \
 --export_type "gated_cnn_seq" \
 --sharing_mode "all_sharing" \
 --export_model_type "gated_cnn_seq" \
 --mask_type "left2right"