mpirun -np 2 \
 -H localhost:2 \
 python ./t2t_bert/distributed_bin/hvd_train_eval_api.py \
 --buckets "/data/xuht" \
 --config_file "./data/textcnn/textcnn.json" \
 --init_checkpoint "" \
 --vocab_file "chinese_L-12_H-768_A-12/vocab.txt" \
 --label_id "/data/xuht/data_security/model/textcnn/data/label_dict.json" \
 --max_length 64 \
 --train_file "data_security/model/textcnn/data/train_tfrecords" \
 --dev_file "data_security/model/textcnn/data/dev_tfrecords" \
 --model_output "data_security/model/textcnn/model/textcnn_20190722" \
 --epoch 50 \
 --num_classes 12 \
 --train_size 6844 \
 --eval_size 767 \
 --batch_size 32 \
 --model_type "textcnn" \
 --if_shard 1 \
 --is_debug 1 \
 --run_type "sess" \
 --opt_type "hvd" \
 --num_gpus 2 \
 --parse_type "parse_batch" \
 --rule_model "normal" \
 --profiler "no" \
 --train_op "adam" \
 --running_type "train" \
 --cross_tower_ops_type "paisoar" \
 --distribution_strategy "MirroredStrategy" \
 --load_pretrained "no" \
 --w2v_path "chinese_L-12_H-768_A-12/vocab_w2v.txt" \
 --with_char "no_char" \
 --input_target "a" \
 --decay "no" \
 --warmup "no" \
 --distillation "normal" \
 --temperature 2.0 \
 --distillation_ratio 0.5 \
 --task_type "single_sentence_classification" \
 --classifier order_classifier \
 --mode 'single_task'


