mpirun -np 2 \
 -H localhost:2 \
 python ./t2t_bert/distributed_bin/hvd_train_eval_api.py \
 --buckets "/data/xuht" \
 --config_file "./data/textcnn_feature_distillation/textcnn.json" \
 --init_checkpoint "" \
 --vocab_file "./data/multi_cased_L-12_H-768_A-12/vocab.txt" \
 --label_id "./data/lazada_multilingual/label_dict.json" \
 --max_length 128 \
 --train_file "lazada/new_data/20190521/data/distillation/st/train_tfrecords" \
 --dev_file "lazada/new_data/20190521/data/distillation/st/dev_tfrecords" \
 --model_output "lazada/new_data/20190521/data/distillation/st/model/textcnn_0521/" \
 --epoch 100 \
 --num_classes 4 \
 --train_size 782340 \
 --eval_size 195588 \
 --batch_size 32 \
 --model_type "textcnn_distillation" \
 --if_shard 1 \
 --is_debug 1 \
 --run_type "sess" \
 --opt_type "hvd" \
 --num_gpus 2 \
 --parse_type "parse_batch" \
 --rule_model "normal" \
 --profiler "no" \
 --train_op "adam" \
 --running_type "train" \
 --cross_tower_ops_type "paisoar" \
 --distribution_strategy "MirroredStrategy" \
 --load_pretrained "no" \
 --w2v_path "multi_cased_L-12_H-768_A-12/vocab_w2v.txt" \
 --with_char "no_char" \
 --input_target "a" \
 --decay "no" \
 --warmup "no" \
 --distillation "distillation" \
 --temperature 2.0 \
 --distillation_ratio 0.5 \
 --task_type "single_sentence_classification" \
 --classifier order_classifier \
 --mode 'single_task'


