python ./t2t_bert/distributed_bin/tf_serving_api.py \
	--buckets "/data/xuht" \
	--vocab "porn/clean_data/textcnn/distillation/char_id.txt" \
	--do_lower_case True \
	--url "10.183.20.12" \
	--port "7901" \
	--model_name "textlstm" \
	--signature_name "serving_default" \
	--versions "1553614002" \
	--task_type "single_sentence_classification" \
	--tokenizer "jieba_char" \
	--with_char "no_char" \
	--output_path "porn/test/test.txt" \
	--input_data "porn/test/result_test.json" \
	--model_type "single_sentence_classification" \
	--max_seq_length 128
